app = "f1kiyoshi"
primary_region = "ord"

[build.args]
MIX_ENV = "prod"

[env]
PHX_HOST = "f1kiyoshi.fly.dev"
PORT = "8080"

[http_service]
auto_start_machines = true
auto_stop_machines = false
force_https = true
internal_port = 8080
min_machines_running = 1
processes = ["app"]

[[vm]]
size = "shared-cpu-1x"
memory = "512mb"